- src/main/java/hudson/plugins/promoted_builds/PromotionProcess.java
There is quite a bit more work to be done to tidy up the UX for PromotionProcesses, but at least we can prevent people from shooting themselves in the foot.
Now, when a user clicks "Build Now", the Javascript will essentially ignore the 404. This is an improvement over the existing functionality which schedules a phantom build which can only be stopped by restarting Jenkins.
As discussed in [JENKINS-24782](https://issues.jenkins-ci.org/browse/JENKINS-24782), this plugin should also customize the left navigation and the context menu, but "I got a thousand problems and fixing-promoted-builds-plugin-UX-in-general ain't one."
> [JENKINS-24782] Prevent phantom builds from being scheduled when PromotionProcesses are built directly.

- src/main/java/hudson/plugins/promoted_builds/Promotion.java
- src/main/java/hudson/plugins/promoted_builds/Status.java
- src/main/resources/hudson/plugins/promoted_builds/PromotedBuildAction/badge.jelly
I wanted to be able to change the icon associated to the build in one of the steps of the promotion process. Currently the plugin allows you define the icon to be displayed on promotion beforehand and it cannot be changed by a groovy build step in the promotion process.
I have added an icon field to promotion class and initialized it with the value of icon from PromotionProcess class. i also modified the Status class to first look for the value of icon in the promotion object and fallback to PromotionProcess object if icon in Promotion object is null.
There is also a check to return null, if the value of icon in Promotion object is set to "none". This is to allow a groovy build step to remove the icon associated with a promoted build.
The change in badge.jelly is to check if the iconUrl …
> allow promotion badge to be modified by groovy build step of promotion process

- src/main/java/hudson/plugins/promoted_builds/Promotion.java
- src/main/java/hudson/plugins/promoted_builds/PromotionProcess.java
- src/test/java/hudson/plugins/promoted_builds/conditions/SelfPromotionTest.java
This should fix the regression introduced in 2.17.
> [JENKINS-22679] Pass the target build parameters to the promotion build when the promotion build doesn't have its own parameters.

- src/main/java/hudson/plugins/promoted_builds/conditions/DownstreamPassCondition.java
- src/test/java/hudson/plugins/promoted_builds/conditions/DownstreamPassConditionTest.java
This only concerns the fallback mode when the upstream and the downstream jobs don't share any fingerprints.
> [FIXED JENKINS-7739] Downstream projects not evaluated recursively

- src/test/java/hudson/plugins/promoted_builds/conditions/DownstreamPassConditionTest.java
This change fixes a test from #57 , which has been merged. The test is flappy, becase there was no rebuild of the dependency graph. In addition, test projects have been renamed for a better readability. 
@reviewbybees @FrantaM
> [JENKINS-7739] - Fix the failing test

- src/main/java/hudson/plugins/promoted_builds/Promotion.java
- src/main/java/hudson/plugins/promoted_builds/conditions/ManualCondition.java
- src/test/java/hudson/plugins/promoted_builds/PromotionEnvironmentVariablesTest.java
It's an update of #52
https://issues.jenkins-ci.org/browse/JENKINS-16063
> [JENKINS-16063] - Inject PROMOTED_USER_ID variable + minor issue fixes

- pom.xml
- src/main/java/hudson/plugins/promoted_builds/tokenmacro/PromotedEnvVarTokenMacro.java
- src/main/resources/hudson/plugins/promoted_builds/tokenmacro/help.jelly
- src/test/java/hudson/plugins/promoted_builds/tokenmacro/PromotedEnvVarTokenMacroTest.java
https://issues.jenkins-ci.org/browse/JENKINS-30411
Promotion is an independent job type, which has its own environment. Several promotion-oriented build steps may need an environment or artifacts of the original builds, so they may call the TokenMacro resolution against the build.
In particular cases we're interested to support environment variables from both Promotion and original build. In such case it would be great to have a PROMOTION_ENV macro, which finds the source promotion job by the current executor context. In such case ENV and PROMOTION_ENV macros will allow to extract variables from both jobs.
Example of the use-case in Deployer Framework Plugin: [PromotionCapabilitiesResolver.java#L172-L186][1] . Here it passes a Build instead of the Promotion to the Engine configuration …
> [FIXED JENKINS-30411] - Add the PROMOTION_ENV token macro

- src/main/java/hudson/plugins/promoted_builds/PromotionProcess.java
Since 1.585, the promotion must explicitly indicate that it can be disabled.
Otherwise, promotions which trigger automatically upon build completion will
execute, even if they're archived.
See hudson.model.AbstractProject#makeDisabled(boolean) for additional details.
> [FIXED JENKINS-27716] - Disable archived promotion jobs

- src/main/java/hudson/plugins/promoted_builds/PromotionProcess.java
- src/main/resources/hudson/plugins/promoted_builds/conditions/SelfPromotionCondition/index.jelly
If a manual promotion has been done, provide its parameters to any other
type of promotion that may trigger the build.
Reword the SelfPromotionCondition failure text to indicate that the
build may still be in progress.
[FIXED JENKINS-29793]
> Provide parameters from manual approval on all promotions

- src/main/java/hudson/plugins/promoted_builds/PromotionProcess.java
This was causing the promotion process to *always* fail when also running
the Build Environment Plugin v1.6.
The Build Environment Plugin will always check if a process has fingerprint
enabled, and this would always throw an exception. The dummy implementation
the fingerprint method should just return false.
> Removed exception throw when calling isFingerprintConfigured

- src/main/java/hudson/plugins/promoted_builds/PromotionProcess.java
getSCM() in a promoted process will return the base SCM
> [FIXED JENKINS-13751] - PromotionProcess returns SCM of its owner

- src/main/java/hudson/plugins/promoted_builds/Promotion.java
Before, `Run.getId()` was returning something like `2012-04-12_17-13-03`, but with the change of [JENKINS-24380](https://wiki.jenkins-ci.org/display/JENKINS/JENKINS-24380+Migration) this is returning just the same than `PROMOTED_NUMBER` env var.
So `PROMOTED_NUMBER= PROMOTED_NUMBER`
```
e.put("PROMOTED_URL",rootUrl+target.getUrl());
e.put("PROMOTED_JOB_NAME", target.getParent().getName());
e.put("PROMOTED_JOB_FULL_NAME", target.getParent().getFullName());
e.put("PROMOTED_NUMBER", Integer.toString(target.getNumber()));
e.put("PROMOTED_ID", target.getId());
e.put("PROMOTED_DISPLAY_NAME", target.getDisplayName());
e.put("PROMOTED_USER_NAME", getUserName());
e.put("PROMOTED_USER_ID", getUserId());
````
The correct fix is to maintain `PROMOTED_ID` for backward compatibility and create a new …
> [FIXED JENKINS-32993] Expose PROMOTED_TIMESTAMP

- src/main/java/hudson/plugins/promoted_builds/Promotion.java
Instead of sorting promotions by id (e.g. #42), sorts promotions by number (e.g. 42). Fixes the display of the promotion list history for a job.
[FIXED JENKINS-31908]
Here is what was displayed : last build is wrong, list is not sorted chronologically.
> [FIXED JENKINS-31908] - Sort Promotion By Number

- pom.xml
- src/main/java/hudson/plugins/promoted_builds/JobPropertyImpl.java
- src/main/java/hudson/plugins/promoted_builds/PromotionProcess.java
- src/main/java/hudson/plugins/promoted_builds/PromotionTargetAction.java
- src/main/java/hudson/plugins/promoted_builds/inheritance/JobPropertyImplSelector.java
- src/test/java/hudson/plugins/promoted_builds/conditions/inheritance/DownstreamPassConditionInheritanceTest.java
- src/test/java/hudson/plugins/promoted_builds/conditions/inheritance/ManualConditionInheritanceTest.java
- src/test/java/hudson/plugins/promoted_builds/conditions/inheritance/SelfPromotionInheritanceTest.java
- src/test/java/hudson/plugins/promoted_builds/inheritance/helpers/InheritanceProjectRule.java
- src/test/java/hudson/plugins/promoted_builds/inheritance/helpers/InheritanceProjectsPair.java
This pull request contains an implementation of extension point to jenkins-inheritance-project-plugin and some changes to JobPropertyImpl construction to allow for interaction with jenkins-inheritance-project-plugin. 
A new constructor has been added that allows reading promotion processes information from the location specified by an existing JobPropertyImpl but makes the JobPropertyImpl instance (and it's promotion processes) independent otherwise. 
Initially I wanted to keep this extension separate (as a plugin) but this proved too difficult because of the hermetization of JobPropertyImpl and its insistence on loading promotion processes on construction. 
Note that there is a problem in jenkins-inheritance-project-plugin and there is an accompanying fix to …
> Add support for running promotions on inheritance projects.

- src/main/java/hudson/plugins/promoted_builds/GlobalBuildPromotedBuilds.java
- src/main/java/hudson/plugins/promoted_builds/Promotion.java
- src/main/resources/hudson/plugins/promoted_builds/GlobalBuildPromotedBuilds/config.jelly
- src/main/resources/hudson/plugins/promoted_builds/GlobalBuildPromotedBuilds/help-dateFormat.html
- src/main/resources/hudson/plugins/promoted_builds/GlobalBuildPromotedBuilds/help-timeZone.html
`PROMOTED_TIMESTAMP` shows the date timestamp in UTC TZ but should work in JDK time zone.
I tried to  use the same format than was before for backward compatibility.
```
2012-04-12_17-13-03
```
@reviewbybees @oleg-nenashev
> [FIXED JENKINS-33147] Customize Date format string and timezone

- pom.xml
- src/main/java/hudson/plugins/promoted_builds/conditions/GroovyCondition.java
- src/main/java/hudson/plugins/promoted_builds/conditions/GroovyConditionDescriptor.java
- src/main/resources/hudson/plugins/promoted_builds/conditions/GroovyCondition/Badge/index.jelly
- src/main/resources/hudson/plugins/promoted_builds/conditions/GroovyCondition/config.jelly
- src/main/resources/hudson/plugins/promoted_builds/conditions/GroovyCondition/help.html
- src/main/resources/hudson/plugins/promoted_builds/conditions/GroovyCondition/index.jelly
- src/main/resources/hudson/plugins/promoted_builds/conditions/Messages.properties
- src/test/java/hudson/plugins/promoted_builds/conditions/GroovyConditionTest.java
- Allow custom conditions for promotions when `script-security` is installed (1.16 was chosen over 1.17 to avoid bumping Jenkins version).
- That condition does not trigger itself (eg. need to be combined with ManualCondition, SelfPromotionCondition or similar)
- The script can also contribute to the environment of the Promotion build (by returning a Map)
- Can customize the label shown on the promotions status page
> Add Groovy script condition

- pom.xml
- src/main/java/hudson/plugins/promoted_builds/Promotion.java
- src/main/java/hudson/plugins/promoted_builds/PromotionCondition.java
- src/main/java/hudson/plugins/promoted_builds/PromotionProcess.java
- src/main/java/hudson/plugins/promoted_builds/PromotionTargetAction.java
- src/main/java/hudson/plugins/promoted_builds/PromotionTrigger.java
- src/main/java/hudson/plugins/promoted_builds/conditions/DownstreamPassCondition.java
- src/main/java/hudson/plugins/promoted_builds/conditions/ManualCondition.java
- src/main/java/hudson/plugins/promoted_builds/parameters/PromotedBuildParameterDefinition.java
- src/main/java/hudson/plugins/promoted_builds/util/JenkinsHelper.java
- src/main/resources/hudson/plugins/promoted_builds/Messages.properties
- src/main/resources/hudson/plugins/promoted_builds/parameters/Messages.properties
- src/test/java/hudson/plugins/promoted_builds/KeepBuildForeverActionTest.java
- src/test/java/hudson/plugins/promoted_builds/PromotionEnvironmentVariablesTest.java
- src/test/java/hudson/plugins/promoted_builds/conditions/DownstreamPassConditionTest.java
- src/test/java/hudson/plugins/promoted_builds/conditions/FixedResultBuilder.java
- src/test/java/hudson/plugins/promoted_builds/conditions/ManualConditionBug22005.java
- src/test/java/hudson/plugins/promoted_builds/conditions/ManualConditionTest.java
- src/test/java/hudson/plugins/promoted_builds/conditions/SelfPromotionTest.java
- src/test/java/hudson/plugins/promoted_builds/conditions/inheritance/DownstreamPassConditionInheritanceTest.java
- src/test/java/hudson/plugins/promoted_builds/conditions/inheritance/SelfPromotionInheritanceTest.java
- src/test/java/hudson/plugins/promoted_builds/tokenmacro/PromotedEnvVarTokenMacroTest.java
> FindBugs: Cleanup issues after the core dependency upgrade

- src/main/java/hudson/plugins/promoted_builds/LastBuildPromotionStatusColumn.java
- src/main/java/hudson/plugins/promoted_builds/PromotionProcess.java
- src/main/java/hudson/plugins/promoted_builds/conditions/DownstreamPassCondition.java
- src/main/resources/hudson/plugins/promoted_builds/PromotedBuildAction/badge.jelly
- src/main/resources/hudson/plugins/promoted_builds/PromotedBuildAction/index.jelly
- src/main/resources/hudson/plugins/promoted_builds/PromotedProjectAction/index.jelly
- src/main/resources/hudson/plugins/promoted_builds/PromotionProcess/help-isVisible.html
- src/main/resources/hudson/plugins/promoted_builds/PromotionProcess/process-config.jelly
- src/main/resources/hudson/plugins/promoted_builds/PromotionStatusColumn/column.jelly
- src/test/java/hudson/plugins/promoted_builds/PromotionProcessTest.java
Add a property "Visible" to promotion processes that resolves parameters (default values of parameters only). If the parameter resolves to false the promotion is not shown in Project, Build and other contexts... 
This is useful in inheritance scenarios where promotion processes are defined in base job (e.g. BASE job has promotion to Dev, Staging, and Production defined) and there are inheriting jobs that just set visibility: e.g.
Stable and Mainline that both inherit from BASE but Stable should show only promotions to Staging and Production and Mainline only to Development.
> Allow to hide some promotion processes based on parameter value.

- src/main/java/hudson/plugins/promoted_builds/integrations/jobdsl/JobDslPromotionProcessConverter.java
- src/test/java/hudson/plugins/promoted_builds/integrations/jobdsl/PromotionsDslContextExtensionTest.java
- src/test/resources/copyartifacts-example-dsl.groovy
https://issues.jenkins-ci.org/browse/JENKINS-34204
@denschu 
I'm not sure what the correct protocol here is (jenkins issue?) but I always prefer a failing test so we'll start there.  
The issue is that jenkins ends up interpreting all configuration as 'latest successful build', regardless of how 'buildSelector' is configured.  It looks like the resulting config.xml of the copyArtifacts step is incorrect.  Specifically, the class of the selector is missing. 
given the following partial dsl:
copyArtifacts('source-job') {
buildSelector {
buildNumber('${PROMOTED_NUMBER}')
}
}
something like this is generated at the top level:
<hudson.plugins.copyartifact.CopyArtifact>
<selector class="hudson.plugins.copyartifact.SpecificBuildSelector">
<buildNumber>${PROMOTED_NUMBER}</buildNumber>
</selector> …
>  [FIXED JENKINS-34204] include node attributes when writing job dsl nodes

- src/main/java/hudson/plugins/promoted_builds/integrations/jobdsl/PromotionsExtensionPoint.java
As per [this comment](https://github.com/jenkinsci/promoted-builds-plugin/commit/327d0233255d0a2c2806c3337daac97e8580905c#commitcomment-17432529). 2.26 throws big scary exceptions.
@reviewbybees esp. @daniel-beck, @oleg-nenashev
> Make PromotionsExtensionPoint an optional extension

- src/main/java/hudson/plugins/promoted_builds/Promotion.java
Acquiring a quick lock causes parallelised builds to back up waiting for
the workspace to become available.  This is because WorkspaceList.allocate
will give executing jobs the first workspace as the given lock is a quick
lock.  Then builds will wait in WorkspaceList.acquire all trying to get
the same workspace.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/promoted-builds-plugin/90)
> Changed to use WorkspaceList.allocate instead of acquire.

- src/main/java/hudson/plugins/promoted_builds/Promotion.java
- src/main/java/hudson/plugins/promoted_builds/PromotionProcess.java
- src/test/java/hudson/plugins/promoted_builds/conditions/ManualConditionTest.java
- src/test/java/hudson/plugins/promoted_builds/conditions/SelfPromotionTest.java
Insertion of ParametersDefinition seems to be unsafe according to the job initialization logic and new TCB plugin options (filter by param values), so I've finally implemented a straightforward fix.
https://issues.jenkins-ci.org/browse/JENKINS-34826
@reviewbybees @amuniz
> [JENKINS-34826] - Prevent failures when using parameters from the promoted build

- src/main/java/hudson/plugins/promoted_builds/PromotedProjectAction.java
The first build was being returned instead of the latest.
History was showing first 10 instead of last 10.
Promotions column had incorrect build number against promotions.
> JENKINS-29358 - fix history, latest build, promotions

- pom.xml
- src/test/java/hudson/plugins/promoted_builds/TestingFrameworkTest.java
This avoids problems caused by mockito-all classes clashing with other testing libraries
> [FIXED JENKINS-39362] Replace mockito-all by mockito-core

- src/main/java/hudson/plugins/promoted_builds/JobPropertyImpl.java
It is probably unnecessary to have the `getOwner` method synchronized.
Credit goes to @jglick as the PR was created as part of a comment he made on [the jira](https://issues.jenkins-ci.org/browse/JENKINS-40552?focusedCommentId=280911&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-280911).
@reviewbybees
> [JENKINS-40552] Remove unnecessary synchronization from method.

- pom.xml
- src/main/java/hudson/plugins/promoted_builds/JobPropertyImpl.java
- src/test/java/hudson/plugins/promoted_builds/ConfigurationDoCheckTest.java
- src/test/java/hudson/plugins/promoted_builds/ConfigurationRoundtripTest.java
- src/test/java/hudson/plugins/promoted_builds/KeepBuildForeverActionTest.java
- src/test/java/hudson/plugins/promoted_builds/PromotedBuildActionTest.java
- src/test/java/hudson/plugins/promoted_builds/PromotionProcessTest.java
- src/test/java/hudson/plugins/promoted_builds/PromotionTargetActionTest.java
- src/test/java/hudson/plugins/promoted_builds/RemoteApiTest.java
- src/test/java/hudson/plugins/promoted_builds/conditions/DownstreamPassConditionTest.java
- src/test/java/hudson/plugins/promoted_builds/conditions/ManualConditionBug22005.java
- src/test/java/hudson/plugins/promoted_builds/conditions/ManualConditionTest.java
- src/test/java/hudson/plugins/promoted_builds/conditions/SelfPromotionTest.java
- src/test/java/hudson/plugins/promoted_builds/conditions/inheritance/DownstreamPassConditionInheritanceTest.java
- src/test/java/hudson/plugins/promoted_builds/conditions/inheritance/SelfPromotionInheritanceTest.java
- src/test/java/hudson/plugins/promoted_builds/integrations/jobdsl/PromotionsDslContextExtensionTest.java
[JENKINS-44266](https://issues.jenkins-ci.org/browse/JENKINS-44266)
- Bump core version.
- Bump some plugins versions.
- Remove HudsonTestCase and use JenkinsRule.
@reviewbybees @oleg-nenashev @kwhetstone
> [JENKINS-44266, JENKINS-36654] Fix PCT for 2.46.2

- src/main/java/hudson/plugins/promoted_builds/conditions/DownstreamPassCondition.java
- src/test/java/hudson/plugins/promoted_builds/conditions/DownstreamPassConditionTest.java
Impersonate SYSTEM in DownstreamPassCondition's RunListener before calling getAllItems for faster ACL checks, and then verify the original authentication had read permission just before considering a build for promotion.
https://issues.jenkins-ci.org/browse/JENKINS-37368
@reviewbybees
> [JENKINS-37368] Improve performance in DownstreamPassCondition RunListener

- pom.xml
- src/main/java/hudson/plugins/promoted_builds/inheritance/JobPropertyImplSelector.java
After the Maven 3.0 release I was able to cleanup the dependency mess in the plugin. Now it looks better, the plugin bundles only findbugs-annotations-1.3.9-1.jar (parent POM defect IIRC) and promoted-builds.jar 
@reviewbybees
> Update Parent POM, resolve upper bound conflicts

- pom.xml
- src/main/java/hudson/plugins/promoted_builds/Promotion.java
- src/main/java/hudson/plugins/promoted_builds/PromotionRebuildValidator.java
- src/main/java/hudson/plugins/promoted_builds/RebuildPromotionSuppressor.java
- src/test/java/hudson/plugins/promoted_builds/PromotionRebuildValidatorTest.java
- src/test/java/hudson/plugins/promoted_builds/PromotionTest.java
See [JENKINS-22068](https://issues.jenkins-ci.org/browse/JENKINS-22068).
This PR does 3 things to fix the issue:
* Promotions with no target now fail when built instead of hanging and blocking the queue.
* Throws a 404 error if a promotion is rebuilt by accessing /rebuild.
* Prevents a RebuildAction from being added to newly created Promotions, so they don't show the "Rebuild" link in the sidebar.
@reviewbybees
> [JENKINS-22068] Fail promotion builds instead of hanging when a promotion is built/rebuilt directly

- src/main/java/hudson/plugins/promoted_builds/PromotionRebuildValidator.java
See [JENKINS-47573](https://issues.jenkins-ci.org/browse/JENKINS-47573).
#107 introduced an [extension](https://github.com/dwnusbaum/promoted-builds-plugin/blob/ca850c37fd636b7bef2c720f7bf55f8b708bffd9/src/main/java/hudson/plugins/promoted_builds/PromotionRebuildValidator.java#L40) of `RebuildValidator` from the optional dependency `rebuild-plugin`.
This PR marks the extension as optional to prevent `NoClassDefFound` errors in the logs.
@reviewbybees
> [JENKINS-47573] Mark extension of class from optional dependency as optional

- src/main/java/hudson/plugins/promoted_builds/integrations/jobdsl/ConditionsContext.java
Fixes the following operations: `selfPromotion()`, `parameterizedSelfPromotion()`, `downstream()`
@reviewbybees @dwnusbaum
> [JENKINS-49433] - Prevent NPEs in JobDSL ConditionContext operations.

- pom.xml
- src/main/java/hudson/plugins/promoted_builds/JobPropertyImplConfigContextResolver.java
- src/test/java/hudson/plugins/promoted_builds/PromotionConfigFilesTest.java
downstream proposal for jenkinsci/config-file-provider-plugin#49.
to implement solution proposed for #104
> [JENKINS-40803] provide a config file resolution context for promotions

- src/test/java/hudson/plugins/promoted_builds/conditions/ManualConditionTest.java
Without the waiting time, the test is passing only once per 10/20 run in my machine.
It works fine with a simple `Thread.sleep(2000)` but using increment of 50ms could speed up the things and at maximum it waits for 5 seconds.
@dwnusbaum can you please have a look ?
@reviewbybees
> Fix a problem of concurrency in one test

- src/main/resources/hudson/plugins/promoted_builds/parameters/PromotedBuildParameterDefinition/index.jelly
- src/main/resources/hudson/plugins/promoted_builds/parameters/PromotedBuildParameterValue/value.jelly
Now promoted build parameter view displays full run name
> Show full display name for runs in promoted build parameters

- src/main/resources/hudson/plugins/promoted_builds/PromotedProjectAction/index.jelly
Now the "UserName" is visible even in the Promotion Status page of a particular "Job".
https://issues.jenkins-ci.org/browse/JENKINS-47207
> FIX JENKINS-47207 : add the username in the job promotion section

- README.md
- src/main/java/hudson/plugins/promoted_builds/Promotion.java
- src/main/java/hudson/plugins/promoted_builds/PromotionProcess.java
- src/main/java/hudson/plugins/promoted_builds/integrations/jobdsl/JobDslPromotionProcess.java
- src/main/java/hudson/plugins/promoted_builds/integrations/jobdsl/JobDslPromotionProcessConverter.java
- src/main/java/hudson/plugins/promoted_builds/integrations/jobdsl/PromotionContext.java
- src/main/java/hudson/plugins/promoted_builds/integrations/jobdsl/PromotionsExtensionPoint.java
- src/main/resources/hudson/plugins/promoted_builds/PromotionProcess/process-config.jelly
- src/test/java/hudson/plugins/promoted_builds/ConfigurationRoundtripTest.java
- src/test/java/hudson/plugins/promoted_builds/PromotionBuildWrapperTest.java
- src/test/java/hudson/plugins/promoted_builds/PromotionProcessTest.java
- src/test/java/hudson/plugins/promoted_builds/integrations/jobdsl/JobDslPromotionProcessConverterTest.java
- src/test/java/hudson/plugins/promoted_builds/integrations/jobdsl/PromotionsDslContextExtensionTest.java
- src/test/resources/buildwrapper-example-dsl.groovy
This PR adds support for build wrappers in the promotion processes. The build wrappers can also be specified for the promotions via JobDSL.
The build wrappers can be configured in a new "Promotion Environment" section of the promotion process configuration.
This is useful e.g. in order to be able to prepare an environment or inject secrets for the promotion.
There are a number of issues calling for this support:
* https://issues.jenkins-ci.org/browse/JENKINS-23977
* https://issues.jenkins-ci.org/browse/JENKINS-25526
* https://issues.jenkins-ci.org/browse/JENKINS-43656
For [JENKINS-14169](https://issues.jenkins-ci.org/browse/JENKINS-14169) this change might provide a workaround by allowing to inject environment vars for the promotion either from the configuration or by injecting them from …
>  Add support for build wrappers in promotions

- src/main/resources/hudson/plugins/promoted_builds/PromotedProjectAction/index.jelly
The pane for the promoted builds history does not have an id and the toggle open/close won't work.
We add an id from the name of the promotion.
> Allow expanding and collapsing the promotion history pane

- src/main/java/hudson/plugins/promoted_builds/PromotedProjectAction.java
…regular build history.
This changes the sort order from ascending by build number to descending by build number (newest on top). This is in line with the default ordering of the build history.
> Sort last promotions list chronologically descending like the regular build history

- README.md
Updated link to the correct Gitter chat channel for the undergoing GSoC Project.
> Update the chat link to direct users to the correct Gitter Channel.

- src/main/java/hudson/plugins/promoted_builds/KeepBuildForeverAction.java
- src/main/java/hudson/plugins/promoted_builds/Promotion.java
- src/main/java/hudson/plugins/promoted_builds/tasks/RedeployBatchTaskPublisher.java
- src/main/resources/hudson/plugins/promoted_builds/Promotion/index.jelly
- src/test/java/hudson/plugins/promoted_builds/PromotedBuildRebuildParameterProviderTest.java
- src/test/java/hudson/plugins/promoted_builds/PromotionBuildWrapperTest.java
- src/test/java/hudson/plugins/promoted_builds/PromotionProcessTest.java
- src/test/java/hudson/plugins/promoted_builds/PromotionRebuildValidatorTest.java
- src/test/java/hudson/plugins/promoted_builds/PromotionTargetActionTest.java
- src/test/java/hudson/plugins/promoted_builds/PromotionTest.java
- src/test/java/hudson/plugins/promoted_builds/conditions/SelfPromotionTest.java
- src/test/java/hudson/plugins/promoted_builds/conditions/inheritance/SelfPromotionInheritanceTest.java
- src/test/java/hudson/plugins/promoted_builds/tokenmacro/PromotedEnvVarTokenMacroTest.java
See [JENKINS-59600](https://issues.jenkins-ci.org/browse/JENKINS-59600).
Since Jenkins 2.138.2 and 2.147, `Run` implements `StaplerProxy` and therefore has a magic `getTarget` method. This clashes with the existing method in `Promotion`, so rename it (but keep the exported name for remote API stability).
This PR underwent only minimal manual testing.
@mention
> [JENKINS-59600, JENKINS-58337, JENKINS-58534] - Fix promotion log visualization with Jenkins 2.138.2+ (regression in 3.3)

- Jenkinsfile
- pom.xml
- src/main/java/hudson/plugins/promoted_builds/KeepBuildForeverAction.java
- src/main/java/hudson/plugins/promoted_builds/Promotion.java
- src/main/java/hudson/plugins/promoted_builds/tasks/RedeployBatchTaskPublisher.java
- src/test/java/hudson/plugins/promoted_builds/PromotedBuildRebuildParameterProviderTest.java
- src/test/java/hudson/plugins/promoted_builds/PromotionBuildWrapperTest.java
- src/test/java/hudson/plugins/promoted_builds/PromotionProcessTest.java
- src/test/java/hudson/plugins/promoted_builds/PromotionRebuildValidatorTest.java
- src/test/java/hudson/plugins/promoted_builds/PromotionTargetActionTest.java
- src/test/java/hudson/plugins/promoted_builds/PromotionTest.java
- src/test/java/hudson/plugins/promoted_builds/conditions/SelfPromotionTest.java
- src/test/java/hudson/plugins/promoted_builds/conditions/inheritance/SelfPromotionInheritanceTest.java
- src/test/java/hudson/plugins/promoted_builds/tokenmacro/PromotedEnvVarTokenMacroTest.java
> [JENKINS-59704] - Restore binary compatibility with Promoted Builds 3.3 and older

- src/test/java/hudson/plugins/promoted_builds/conditions/ManualConditionTest.java
- src/test/java/hudson/plugins/promoted_builds/conditions/inheritance/ManualConditionInheritanceTest.java
`assertEquals` is used for similar assertions throughout the code base.
I'm leaving the checklist here. I think my changes are not breaking, just conforming to the best practice use of `Assert`.
> Use assertEquals instead of assertTrue in tests.

- src/test/java/hudson/plugins/promoted_builds/integrations/jobdsl/JobDslManualConditionConverterTest.java
- src/test/java/hudson/plugins/promoted_builds/integrations/jobdsl/JobDslPromotionProcessConverterTest.java
both JobDslManualConditionConverterTest and JobDslPromotionProcessConverterTest would fail when run against a newer Jenkins core (for example via the PCT).  The cause was that annotations are no longer automatically processed when serialising / deserialising code.
Fixed this so that we regestier the classes wit interesting annotations.
Also updated the test to use hamcreset to get better errors than binary
pass/fail
See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).
@oleg-nenashev
> Fix incompatibility with Jenkins 2.266 and higher in test code.

- pom.xml
As reported by @jtnord, otherwise tests fail with `-Djenkins.version=2.278` due to
```
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: hudson.model.Queue$WaitingItem.getFuture()Ljava/util/concurrent/Future;
at hudson.remoting.AsyncFutureImpl.get(AsyncFutureImpl.java:81)
at org.jvnet.hudson.test.JenkinsRule.assertBuildStatus(JenkinsRule.java:1332)
at org.jvnet.hudson.test.JenkinsRule.assertBuildStatusSuccess(JenkinsRule.java:1361)
at org.jvnet.hudson.test.JenkinsRule.buildAndAssertSuccess(JenkinsRule.java:1373)
at hudson.plugins.promoted_builds.conditions.inheritance.DownstreamPassConditionInheritanceTest.shouldEvaluateUpstreamRecursively(DownstreamPassConditionInheritanceTest.java:66)
at …
Caused by: java.lang.NoSuchMethodError: …
```
> Use newer `project-inheritance` dependency (19.08.02 instead of 1.5.3)

- src/main/resources/hudson/plugins/promoted_builds/Messages.properties
- src/main/resources/hudson/plugins/promoted_builds/PromotionProcess/help-assignedLabelString.html
- src/main/resources/hudson/plugins/promoted_builds/PromotionProcess/process-config.jelly
- src/test/resources/complex-example-dsl.groovy
See [JENKINS-42816](https://issues.jenkins.io/browse/JENKINS-42816).
- use agent terminology
- the help message for label was not displayed, added the missing field value to have it displayed.
I have run tests locally, it seems ok
Screenshot of the help message (using `mvn hpi:run`):
@mention
> [JENKINS-42816] use agent terminology and fix help for label.

- src/test/java/hudson/plugins/promoted_builds/PromotedBuildActionTest.java
PromotedBuildActionTest fails for jenkins versions > 2.221 due to UI change.
see https://github.com/jenkinsci/jenkins-test-harness/pull/200
@jglick
> fix test download of svg images

- Jenkinsfile
- pom.xml
- src/main/java/hudson/plugins/promoted_builds/Promotion.java
- src/test/java/hudson/plugins/promoted_builds/ConfigurationDoCheckTest.java
- src/test/java/hudson/plugins/promoted_builds/PromotionTest.java
Refile of https://github.com/jenkinsci/promoted-builds-plugin/pull/158 as a maintainer to add Jenkinsfile refinements
Update build infrastructure for compatibility with JDK11. This requires to remove Promotion#getTarget as it conflicts with evolutions done in Jenkins core.
Downstream plugins will need to adjust to this.
See [JENKINS-67045](JENKINS-67045).
> [JENKINS-67045] Remove Promotion#getTarget

- src/main/java/hudson/plugins/promoted_builds/Promotion.java
- Given [JENKINS-17200](https://issues.jenkins-ci.org/browse/JENKINS-17200) is currently unfixed we are forcing eager loading of properties relevant to Promoted Builds Plugin so that they are available to the JcasC. 
- Prior to this eager load the `Promote` property was unavailable for in the Global Security Matrix. 
- An similar fix made within core Jenkins to fix property loading: https://github.com/jenkinsci/jenkins/pull/5723
- Discussion between Slack developers and Jenkins collaborators which led us to this fix: https://github.com/jenkinsci/configuration-as-code-plugin/issues/2005
- [✅] Pull request title represents the changelog entry which will be used in Release Notes. JIRA issue is a part of the title (see existing PRs as examples)
- [✅] Please describe what you did. Short …
> Force lazy loading of Promoted Builds Plugin properties so they are available to JCasC

- pom.xml
#247 fails because the dependency `org.jenkins-ci.plugins:parameterized-trigger:jar:2.46` requires Jenkins `2.387.3` or higher.
I propose then to amend the dependabot PR with this one.
- ~~Test automation, if relevant. We expect autotests for all new features or complex bugfixes~~
- ~~Documentation if relevant (new features). We want to use Documentation-as-Code, just put docs to README or to new Doc files~~
- ~~Javadoc for new APIs. Any public/protected method is considered as API unless annotated by `Restricted` ([docs](https://kohsuke.org/access-modifier/apidocs/org/kohsuke/accmod/AccessRestriction.html))~~
@mention
> chore(dependencies): Require 2.387.3 as minimum Jenkins version

- src/main/java/hudson/plugins/promoted_builds/CopyListener.java
See [JENKINS-69711](https://issues.jenkins.io/browse/JENKINS-69711). Fixes a regression introduced in https://github.com/jenkinsci/promoted-builds-plugin/pull/217. Tested by reproducing the problem as described in the bug and verifying the problem was no longer reproducible after this PR.
> [JENKINS-69711] Promotion configuration is lost when creating a new job by copy

- src/main/resources/hudson/plugins/promoted_builds/Promotion/index.jelly
The change proposed replaces the EOL spinner.gif with the drop-in Jelly tag replacement.
> Replace EOL spinner.gif with drop-in Jelly tag

- src/main/resources/hudson/plugins/promoted_builds/PromotedBuildAction/index.jelly
- src/main/webapp/css/promoted-builds.css
In the GUI of the promotions page , there is no clear separation between the various promotions, and sometimes you may press the wrong one. 
This PR adds a container to the various sections of the page, changing the style as seen in the images below
See [JENKINS-72461](https://issues.jenkins-ci.org/browse/JENKINS-72461).
@mention
> improve the UIX promotions page

- pom.xml
- src/main/java/hudson/plugins/promoted_builds/PromotionCondition.java
- src/main/java/hudson/plugins/promoted_builds/PromotionProcess.java
- src/main/java/hudson/plugins/promoted_builds/conditions/DownstreamPassCondition.java
- src/test/java/hudson/plugins/promoted_builds/PromotedBuildRebuildParameterProviderTest.java
[Installation statistics](https://stats.jenkins.io/pluginversions/promoted-builds.html) show that 85% of the installations of the most recent release (delivered 3 months ago) are already running Jenkins 2.440.3 or newer.  Users that are upgrading to the most recent release of the plugin are also upgrading to the most recent Jenkins releases.
Removes unnecessary declarations of mockito-core and hamcrest since those are provided by the parent pom.
Removes unnecessary exclusions from other dependencies.
Annotates deprecated methods to silence compiler warnings
Replace rebuild web action in test with freestyle build
Intentionally sacrifices some code coverage of the rebuild plugin so that I don't need to find an alternate way to invoke rebuild.  The previously tested web action is …
> Require Jenkins 2.440.3 or newer

- pom.xml
- src/main/java/hudson/plugins/promoted_builds/GlobalBuildPromotedBuilds.java
- src/main/java/hudson/plugins/promoted_builds/JobPropertyImpl.java
- src/main/java/hudson/plugins/promoted_builds/PromotedBuildAction.java
- src/main/java/hudson/plugins/promoted_builds/PromotedProjectAction.java
- src/main/java/hudson/plugins/promoted_builds/Promotion.java
- src/main/java/hudson/plugins/promoted_builds/PromotionProcess.java
- src/main/java/hudson/plugins/promoted_builds/Status.java
- src/main/java/hudson/plugins/promoted_builds/conditions/DownstreamPassCondition.java
- src/main/java/hudson/plugins/promoted_builds/conditions/ManualCondition.java
- src/main/java/hudson/plugins/promoted_builds/conditions/UpstreamPromotionCondition.java
- src/main/java/hudson/plugins/promoted_builds/parameters/PromotedBuildParameterDefinition.java
- src/main/java/hudson/plugins/promoted_builds/tasks/RedeployBatchTaskPublisher.java
- src/test/java/hudson/plugins/promoted_builds/PromotionProcessTest.java
Migrate from deprecated EE 8 functionality to non-deprecated EE 9 equivalents.
> Migrate from EE 8 to EE 9
