jenkinsci/promoted-builds-plugin

pom.xml
src/main/java/hudson/plugins/promoted_builds/JobPropertyImpl.java
src/main/java/hudson/plugins/promoted_builds/KeepBuildForeverAction.java
src/main/java/hudson/plugins/promoted_builds/Promotion.java
src/main/java/hudson/plugins/promoted_builds/PromotionCause.java
src/main/java/hudson/plugins/promoted_builds/PromotionProcess.java
src/main/java/hudson/plugins/promoted_builds/Status.java
src/main/java/hudson/plugins/promoted_builds/conditions/DownstreamPassCondition.java
src/main/java/hudson/plugins/promoted_builds/conditions/ManualCondition.java
src/main/java/hudson/plugins/promoted_builds/conditions/ParameterizedSelfPromotionCondition.java

The code is not clean according to the local run

Enable FindBugs in the plugin, generate XML reports

---

pom.xml
src/main/java/hudson/plugins/promoted_builds/PromotedProjectAction.java
src/main/java/hudson/plugins/promoted_builds/PromotionStatusColumn.java
src/main/java/hudson/plugins/promoted_builds/Status.java
src/main/resources/hudson/plugins/promoted_builds/Messages.properties
src/main/resources/hudson/plugins/promoted_builds/PromotionStatusColumn/column.jelly
src/main/resources/hudson/plugins/promoted_builds/PromotionStatusColumn/column.properties
src/main/resources/hudson/plugins/promoted_builds/PromotionStatusColumn/columnHeader.jelly
src/main/resources/hudson/plugins/promoted_builds/PromotionStatusColumn/columnHeader.properties
src/main/resources/hudson/plugins/promoted_builds/PromotionStatusColumn/config.jelly
src/main/resources/hudson/plugins/promoted_builds/PromotionStatusColumn/config.properties

alternative to pull request #30. see also https://issues.jenkins-ci.org/browse/JENKINS-3549

JENKINS-3549: display promotion stars on the view.

---

pom.xml
src/main/java/hudson/plugins/promoted_builds/parameters/PromotedBuildParameterDefinition.java
src/main/java/hudson/plugins/promoted_builds/util/ItemPathResolver.java
src/main/webapp/parameter/help-job.html
src/test/java/hudson/plugins/promoted_builds/util/ItemPathResolverTest.java

Follow-up to https://github.com/jenkinsci/promoted-builds-plugin/pull/47
- Nice2have: Get the confirmation from @daniel-beck that the fix addresses his concerns
@daniel-beck , Is it what you would like to see in the plugin?

[JENKINS-25011] - Folders and the relative addressing support

---

src/main/resources/hudson/plugins/promoted_builds/PromotedProjectAction/index.jelly
src/main/webapp/css/promoted-builds.css

[JENKINS-31320](https://issues.jenkins-ci.org/browse/JENKINS-31320)
@reviewbybees, specially @oleg-nenashev

[JENKINS-31320] Layout broken as of 1.619+

---

src/main/java/hudson/plugins/promoted_builds/Status.java
src/main/java/hudson/plugins/promoted_builds/conditions/ManualCondition.java

https://issues.jenkins-ci.org/browse/JENKINS-31356
doBuild method checks an user for only project permission level. It has to check the user for the approver list as well.

[JENKINS-31356] Manual condition and re-execute promotion bug.

---

src/main/java/hudson/plugins/promoted_builds/PromotionProcess.java

Reverts jenkinsci/promoted-builds-plugin#73

[FIXED JENKINS-32006] - Revert "[FIXED JENKINS-13751] - PromotionProcess returns SCM of its owner"

---

src/main/resources/hudson/plugins/promoted_builds/PromotedBuildAction/index.jelly

[JENKINS-31406](https://issues.jenkins-ci.org/browse/JENKINS-31406)
Related to [JENKINS-31320](https://issues.jenkins-ci.org/browse/JENKINS-31320)
@reviewbybees, specially @oleg-nenashev 
Easier to review if you use `w=1`

[JENKINS-31406] Jelly tag l:pane breaks the UI

---

src/main/java/hudson/plugins/promoted_builds/Promotion.java

Should solve:
https://issues.jenkins-ci.org/browse/JENKINS-29586
https://github.com/dblock/jenkins-ansicolor-plugin/issues/34
Compiled & tested on my instance, looks like it does the job.

[JENKINS-29586] Add support for ANSI color output in console

---

src/test/java/hudson/plugins/promoted_builds/PromotionProcessTest.java

Updating the tests to work on windows so CI builds pass.
@reviewbybees

Fix tests on windows

---

src/main/java/hudson/plugins/promoted_builds/Status.java

https://issues.jenkins-ci.org/browse/JENKINS-48634
@dwnusbaum @reviewbybees

[JENKINS-48634] - implement more robust form handling in Status#doBuild()

---

pom.xml

Just a minor update towards the next release

Update Plugin POM

---

README.md

Link GSoC's undergoing project's- (Artifact Promotion Plugin For Jenkins Pipeline) gitter channel with the promoted-builds-plugin repository.

Link with the Chat Channels

---

CONTRIBUTING.md
README.md
README.txt

This sis a minor cleanup of the plugin documentation. More changes will be submitted later as a follow-up.

Cleanup README, detach CONTRIBUTING.md and add shields

---

Jenkinsfile
pom.xml
src/main/java/hudson/plugins/promoted_builds/JobPropertyImpl.java
src/main/java/hudson/plugins/promoted_builds/Promotion.java
src/main/java/hudson/plugins/promoted_builds/PromotionCondition.java
src/main/java/hudson/plugins/promoted_builds/PromotionProcess.java
src/main/java/hudson/plugins/promoted_builds/PromotionTargetAction.java
src/main/java/hudson/plugins/promoted_builds/PromotionTrigger.java
src/main/java/hudson/plugins/promoted_builds/conditions/DownstreamPassCondition.java
src/main/java/hudson/plugins/promoted_builds/conditions/GroovyCondition.java
src/main/java/hudson/plugins/promoted_builds/conditions/GroovyConditionDescriptor.java
src/main/java/hudson/plugins/promoted_builds/conditions/ManualCondition.java
src/main/java/hudson/plugins/promoted_builds/integrations/jobdsl/JobDslPromotionProcessConverter.java
src/main/java/hudson/plugins/promoted_builds/parameters/PromotedBuildParameterDefinition.java
src/main/java/hudson/plugins/promoted_builds/tasks/RedeployBatchTaskPublisher.java
src/main/java/hudson/plugins/promoted_builds/util/ItemPathResolver.java
src/main/java/hudson/plugins/promoted_builds/util/JenkinsHelper.java
src/main/resources/hudson/plugins/promoted_builds/Messages.properties
src/test/java/hudson/plugins/promoted_builds/PromotionTest.java
src/test/java/hudson/plugins/promoted_builds/RemoteApiTest.java
src/test/java/hudson/plugins/promoted_builds/conditions/inheritance/ManualConditionInheritanceTest.java
src/test/java/hudson/plugins/promoted_builds/integrations/jobdsl/PromotionsDslContextExtensionTest.java

Just a facelift of the plugin, which should simplify the refactoring work by @dernDren161

Update Jenkins Core requirement to 2.138.4, use the modern Parent POM

---

src/main/java/hudson/plugins/promoted_builds/JobPropertyImpl.java
src/main/java/hudson/plugins/promoted_builds/PromotionCause.java
src/main/java/hudson/plugins/promoted_builds/PromotionProcess.java
src/main/java/hudson/plugins/promoted_builds/integrations/jobdsl/PromotionsExtensionPoint.java
src/test/java/hudson/plugins/promoted_builds/KeepBuildForeverActionTest.java
src/test/java/hudson/plugins/promoted_builds/PromotionProcessTest.java

Various clean-ups based on IntelliJ.

Java8 lambdas

---

src/main/resources/hudson/plugins/promoted_builds/PromotionProcess/process-config.jelly
src/main/resources/hudson/plugins/promoted_builds/PublisherImpl/config.jelly
src/main/resources/lib/promoted_builds/blockWrapper.jelly

See [JENKINS-62817](https://issues.jenkins-ci.org/browse/JENKINS-62817).
cc @oleg-nenashev 
@mention

JENKINS-62817 Tables to divs compat

---

.mvn/extensions.xml
.mvn/maven.config
pom.xml
src/main/java/hudson/plugins/promoted_builds/integrations/jobdsl/PromotionsExtensionPoint.java

No idea why #82 added this but it breaks PCT against https://github.com/jenkinsci/jenkins/pull/4944.

Removing explicit dep on xstream

---

CHANGELOG.md

remove badge from CHANGELOG

---

src/main/java/hudson/plugins/promoted_builds/CopyListener.java

https://github.com/jenkinsci/jenkins/pull/6272#discussion_r940710074

Adapt to https://github.com/jenkinsci/jenkins/pull/6272

---

.mvn/extensions.xml
pom.xml

Update plugin parent POM and BOM

---

pom.xml
src/main/java/hudson/plugins/promoted_builds/JobPropertyImpl.java
src/main/java/hudson/plugins/promoted_builds/PromotedBuildAction.java
src/main/java/hudson/plugins/promoted_builds/PromotedProjectAction.java
src/main/java/hudson/plugins/promoted_builds/Promotion.java
src/main/java/hudson/plugins/promoted_builds/PromotionCondition.java
src/main/java/hudson/plugins/promoted_builds/PromotionPermissionHelper.java
src/main/java/hudson/plugins/promoted_builds/PromotionProcess.java
src/main/java/hudson/plugins/promoted_builds/PromotionTargetAction.java
src/main/java/hudson/plugins/promoted_builds/Status.java
src/main/java/hudson/plugins/promoted_builds/conditions/DownstreamPassCondition.java
src/main/java/hudson/plugins/promoted_builds/conditions/GroovyCondition.java
src/main/java/hudson/plugins/promoted_builds/conditions/ManualCondition.java
src/main/java/hudson/plugins/promoted_builds/integrations/jobdsl/ConditionsContext.java
src/main/java/hudson/plugins/promoted_builds/integrations/jobdsl/JobDslPromotionProcessConverter.java
src/main/java/hudson/plugins/promoted_builds/integrations/jobdsl/PromotionsContext.java
src/main/java/hudson/plugins/promoted_builds/parameters/PromotedBuildParameterDefinition.java
src/main/java/hudson/plugins/promoted_builds/util/ItemPathResolver.java
src/main/java/hudson/plugins/promoted_builds/util/JenkinsHelper.java
src/test/java/hudson/plugins/promoted_builds/ConfigurationDoCheckTest.java
src/test/java/hudson/plugins/promoted_builds/ConfigurationRoundtripTest.java
src/test/java/hudson/plugins/promoted_builds/PromotedBuildActionTest.java
src/test/java/hudson/plugins/promoted_builds/PromotedBuildRebuildParameterProviderTest.java
src/test/java/hudson/plugins/promoted_builds/PromotionTest.java
src/test/java/hudson/plugins/promoted_builds/RemoteApiTest.java
src/test/java/hudson/plugins/promoted_builds/conditions/ManualConditionBug22005.java
src/test/java/hudson/plugins/promoted_builds/conditions/ManualConditionTest.java
src/test/java/hudson/plugins/promoted_builds/conditions/inheritance/ManualConditionInheritanceTest.java
src/test/java/hudson/plugins/promoted_builds/integrations/jobdsl/PromotionsDslContextExtensionTest.java
src/test/java/hudson/plugins/promoted_builds/util/ItemPathResolverTest.java

- Remove usages of Guava
- Replace JSR 305 annotations with SpotBugs annotations
- Latest parent POM and BOM
- HtmlUnit migration
Tests pass locally.
@mention

Modernize plugin for June 2023

---

src/test/java/hudson/plugins/promoted_builds/ConfigurationDoCheckTest.java
src/test/java/hudson/plugins/promoted_builds/ConfigurationRoundtripTest.java
src/test/java/hudson/plugins/promoted_builds/KeepBuildForeverActionTest.java
src/test/java/hudson/plugins/promoted_builds/LastBuildPromotionStatusColumnTest.java
src/test/java/hudson/plugins/promoted_builds/PromotedBuildActionTest.java
src/test/java/hudson/plugins/promoted_builds/PromotedBuildRebuildParameterProviderTest.java
src/test/java/hudson/plugins/promoted_builds/PromotionBuildWrapperTest.java
src/test/java/hudson/plugins/promoted_builds/PromotionConfigFilesTest.java
src/test/java/hudson/plugins/promoted_builds/PromotionEnvironmentVariablesTest.java
src/test/java/hudson/plugins/promoted_builds/PromotionProcessTest.java
src/test/java/hudson/plugins/promoted_builds/PromotionRebuildValidatorTest.java
src/test/java/hudson/plugins/promoted_builds/PromotionTargetActionTest.java
src/test/java/hudson/plugins/promoted_builds/PromotionTest.java
src/test/java/hudson/plugins/promoted_builds/RemoteApiTest.java
src/test/java/hudson/plugins/promoted_builds/TestingFrameworkTest.java
src/test/java/hudson/plugins/promoted_builds/conditions/DownstreamPassConditionTest.java
src/test/java/hudson/plugins/promoted_builds/conditions/FixedResultBuilder.java
src/test/java/hudson/plugins/promoted_builds/conditions/GroovyConditionTest.java
src/test/java/hudson/plugins/promoted_builds/conditions/ManualConditionBug22005.java
src/test/java/hudson/plugins/promoted_builds/conditions/ManualConditionTest.java
src/test/java/hudson/plugins/promoted_builds/conditions/SelfPromotionTest.java
src/test/java/hudson/plugins/promoted_builds/integrations/jobdsl/JobDslManualConditionConverterTest.java
src/test/java/hudson/plugins/promoted_builds/integrations/jobdsl/JobDslPromotionProcessConverterTest.java
src/test/java/hudson/plugins/promoted_builds/integrations/jobdsl/PromotionsDslContextExtensionTest.java
src/test/java/hudson/plugins/promoted_builds/tokenmacro/PromotedEnvVarTokenMacroTest.java
src/test/java/hudson/plugins/promoted_builds/util/ItemPathResolverTest.java

This PR aims to migrate all tests to JUnit5. Changes include:
* Migrate annotations and imports
* Migrate assertions
* Remove public visibility for test classes and methods
* Minor clean up
I am well aware that this is a quite large changeset however I hope that there is still interest in this PR and it will be reviewed.
If there are any questions, please do not hesitate to ping me.

Migrate tests to JUnit5

---

src/main/resources/hudson/plugins/promoted_builds/Promotion/index.jelly

Migrate to EE 9 in Jelly view
